alias cl='clear'
alias ll='ls -la'

alias gcam='git commit -am'
alias gcm='git commit -m'
alias ga='git add'
alias gs='git status'
alias gp='git push'
alias gpp='git pull'
alias gcb='git checkout -b'
alias gc='git checkuot'
alias gd='git diff'
alias gs='git switch'

alias nrs='npm run start'
